services:
    Faker\Generator: ~

    EmilienPuget\FakerProvider\SymfonyPasswordProvider:
        arguments:
            - '@nelmio_alice.faker.generator'
            - '@security.encoder_factory.generic'
        public: true
        tags: ['nelmio_alice.faker.provider']